server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启feign对sentinel的支持
hm:
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
  db:
    database: hm-cart
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090  #sentinel控制台地址
      http-method-specify: true # 开启请求方式前缀
# 线程隔离配置
#  tomcat:
#    threads:
#      max: 25 # 允许的最大线程数 默认值8192
#    accept-count: 25 # 最大排队等待数量
#    max-connections: 100 # 允许的最大连接
